http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:
        realm: Traefik2 Basic Auth
        usersFile: /shared/.htpasswd
    middlewares-oauth:
      forwardAuth:
        address: http://oauth:4181
        trustForwardHeader: true
        authResponseHeaders:
          - X-Forwarded-User
    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    middlewares-https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    middlewares-secure-headers:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - OPTIONS
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        # accessControlAllowOrigin: "*"
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        browserXssFilter: true
        forceSTSHeader: true
        stsPreload: true
        stsIncludeSubdomains: true
        sslRedirect: true
        stsSeconds: 31536000
        # featurePolicy: >-
        #   camera 'none'; geolocation 'none'; microphone 'none';
        #   payment 'none'; usb 'none'; vr 'none';
        permissionsPolicy: >-
          camera=(), geolocation=(self "https://davydehaas.nl"), microphone=(), 
          payment=(), usb=(), vr=(),
        customFrameOptionsValue: SAMEORIGIN
        contentSecurityPolicy: "upgrade-insecure-requests" always;
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          Cache-Control: "no-cache, max-age=0" always;
