# nano /reverse-proxy/rules/middleware-chains.yml
http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - compress
          - rate-limit
          - retry
          - secure-headers
    chain-basic-auth:
      chain:
        middlewares:
          - compress-response
          - rate-limit
          - retry
          - secure-headers
          - basic-auth
    chain-authelia:
      chain:
        middlewares:
          - compress
          - rate-limit
          - retry
          - secure-headers
          - authelia
    chain-oauth:
      chain:
        middlewares:
          - compress
          - rate-limit
          - retry
          - secure-headers
          - oauth
    chain-nextcloud:
      chain:
        middlewares:
          - rate-limit
          - retry
          - secure-headers
          - nextcloud
