# nano /reverse-proxy/rules/middleware-chains.yml
http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - compress-middleware
          - rate-limit-middleware
          - retry-middleware
          - secure-headers-middleware

    chain-basic-auth:
      chain:
        middlewares:
          - compress-middleware
          - rate-limit-middleware
          - retry-middleware
          - secure-headers-middleware
          - basic-auth-middleware

    chain-authelia:
      chain:
        middlewares:
          - compress-middleware
          - rate-limit-middleware
          - retry-middleware
          - secure-headers-middleware
          - authelia-middleware

    chain-error-pages:
      chain:
        middlewares:
          - error-pages-middleware

    chain-oauth:
      chain:
        middlewares:
          - compress-middleware
          - rate-limit-middleware
          - retry-middleware
          - secure-headers-middleware
          - oauth-middleware

    chain-nextcloud:
      chain:
        middlewares:
          - rate-limit-middleware
          - retry-middleware
          - secure-headers-middleware
          - nextcloud-middleware
