http:
  middlewares:
    # --- AUTHENTICATION --- 
    basic-auth-middleware:
      basicAuth:
        realm: Traefik2 Basic Auth
        usersFile: /shared/.htpasswd
        
    authelia-middleware:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://authelia.davydehaas.nl/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
          
    oauth-middleware:
      forwardAuth:
        address: http://oauth:4181
        trustForwardHeader: true
        authResponseHeaders:
          - X-Forwarded-User
          
    # --- SETTINGS ---
    buffering-middleware:
      buffering:
        retryExpression: "IsNetworkError() && Attempts() < 2"
        maxRequestBodyBytes: 2000000
        memRequestBodyBytes: 2000000
        maxResponseBodyBytes: 2000000
        memResponseBodyBytes: 2000000
    
    compress-middleware:
      compress:
        minResponseBodyBytes: 1024
        excludedContentTypes:
          - text/event-stream

    circuit-breaker-middleware:
      circuitBreaker:
        expression: "LatencyAtQuantileMS(50.0) > 100"

    errorpage-middleware:
      errors:
        status:
          - "400-499"
        service: serviceError
        query: "/{status}.html"

    rate-limit-middleware:
      rateLimit:
        average: 100
        period: 1m
        burst: 50

    retry-middleware:
      retry:
        attempts: 4
        initialInterval: 100ms

    # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#
    nextcloud-middleware:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"
        
    # --- SECURITY ---
    secure-headers-middleware:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - OPTIONS
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        accessControlAllowOriginList: 
          - https://davydehaas.nl
          - https://*.davydehaas.nl
        accessControlMaxAge: 100
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          Cache-Control: no-cache, max-age=0
          Content-Security-Policy: upgrade-insecure-requests
          Cross-Origin-Embedder-Policy: unsafe-none
          Cross-Origin-Opener-Policy: unsafe-none
          Cross-Origin-Resource-Policy: same-site
          Expect-CT: max-age=0;
          Permissions-Policy: camera=(), geolocation=(), microphone=(), payment=(), usb=(), vr=()
          Referrer-Policy: strict-origin-when-cross-origin
          Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
          Vary: ORIGIN
          X-Content-Type-Options: nosniff
          X-Frame-Options: SAMEORIGIN
          X-Robots-Tag: none
          X-XSS-Protection: 1; mode=block
        sslRedirect: true
