http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:
        realm: Traefik2 Basic Auth
        usersFile: /shared/.htpasswd
    middlewares-oauth:
      forwardAuth:
        address: http://oauth:4181
        trustForwardHeader: true
        authResponseHeaders:
          - X-Forwarded-User
    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    middlewares-https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    middlewares-secure-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          Cache-Control: no-cache, max-age=0
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - OPTIONS
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        accessControlAllowOriginList: 
          - https://davydehaas.nl
          - https://*.davydehaas.nl
        accessControlMaxAge: 100
        addVaryHeader: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: SAMEORIGIN
        contentTypeNosniff: true
        customBrowserXssValue: 1; mode=block
        contentSecurityPolicy: upgrade-insecure-requests
        referrerPolicy: no-referrer
        # featurePolicy: >-
        #   camera 'none'; geolocation 'none'; microphone 'none';
        #   payment 'none'; usb 'none'; vr 'none';
        permissionsPolicy: >-
          camera=(), geolocation=(), microphone=(), 
          payment=(), usb=(), vr=(),
