version: '3.6'
services:
  reverse-proxy:
    container_name: reverse-proxy # Set container name
    image: reverse-proxy # Set image
    build: . # Build the 
    restart: always # Set restart policy
    networks:
      - host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/ # Pass letsencrypt keys
