version: "3.8"
services:
  reverse-proxy:
    image: davydehaas98/reverse-proxy:${DOCKER_TAG}
    container_name: reverse-proxy
    restart: unless-stopped
    volumes:
    # - /reverse-proxy/etc/nginx:/etc/nginx # Configuration files
    # - /reverse-proxy/var/www:/var/www # Default websites
    - /root/.acme.sh:/etc/ssl # Pass SSL certificates
    ports:
    - 80:80
    - 443:443
networks:
  media-server:
    external: true
    name: media-server
  server:
    external: true
    name: server_default