version: '3'
services:
  reverse-proxy:
    build: .
    image: reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    container_name: reverse-proxy
    restart: always
