version: '3.6'
services:
  reverse-proxy:
    container_name: reverse-proxy # Set container name
    image: reverse-proxy # Set image
    build: .
    restart: unless-stopped # Set restart policy
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /certs:/etc/letsencrypt # Pass letsencrypt keys