version: '3'
services:
  reverse-proxy:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/davydehaas.nl:/etc/nginx/conf.d
    container_name: reverse-proxy
    restart: always
