version: "3.8"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: davydehaas98/reverse-proxy
    restart: unless-stopped # Set restart policy
    network_mode: host # https://docs.docker.com/network/host/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/.acme.sh:/etc/ssl # Pass SSL certificates
