version: '3.6'
services:
  reverse-proxy:
    container_name: reverse-proxy # Set container name
    image: davydehaas98/reverse-proxy:latest # Set image
    build: .
    restart: unless-stopped # Set restart policy
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/.acme.sh:/certs # Pass SSL certificates
      #- /etc/letsencrypt:/certs # Pass letsencrypt keys
