version: "3.9"
services:
  reverse-proxy:
    image: traefik:2.10.5
    container_name: reverse-proxy
    restart: unless-stopped
    cpus: 0.01
    mem_limit: 256m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 3179:3179/tcp
      - 3179:3179/udp
    volumes:
      # touch ${USER_DIR}/acme/acme.json
      # chmod 600 ${USER_DIR}/acme/acme.json
      - ${USER_DIR}/acme/acme.json:/acme.json
      - ${USER_DIR}/config:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --configFile=/config/traefik.yml
      - --certificatesResolver.dns-resolver-cloudflare.acme.email=${CLOUDFLARE_EMAIL}
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.${DOMAIN_NAME}`)
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.middlewares=chain-authelia@file
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN_NAME}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN_NAME}
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    
  nginx-error-pages:
    image: nginx:1.25.3
    container_name: nginx-error-pages
    restart: unless-stopped
    cpus: 0.01
    mem_limit: 32m
    volumes:
      - ${USER_DIR}/config/nginx:/usr/share/nginx:ro
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.error-pages.entrypoints=web
      - traefik.http.routers.error-pages.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.error-pages.priority=1
      - traefik.http.routers.error-pages.middlewares=error-pages@docker
      - traefik.http.middlewares.error-pages.errors.status=400-599
      - traefik.http.middlewares.error-pages.errors.query=/{status}.html
      - traefik.http.middlewares.error-pages.errors.services=error-pages@docker
      - traefik.http.services.error-pages.loadbalancer.server.port=80

  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cf-ddns
    restart: unless-stopped
    cpus: 0.01
    mem_limit: 8m
    environment:
      - API_KEY=${CLOUDFLARE_API_TOKEN}
      - ZONE=${DOMAIN_NAME}
      - PROXIED=false
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1
    labels:
      - diun.enable=true
      
  # Cloudflare-Companion - Automatic CNAME DNS Creation
  cf-companion:
    image: tiredofit/traefik-cloudflare-companion:7.1.1
    container_name: cf-companion
    restart: unless-stopped
    cpus: 0.01
    mem_limit: 128m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - TRAEFIK_VERSION=2
      - CF_EMAIL=${CLOUDFLARE_EMAIL} # Same as traefik
      - CF_TOKEN=${CLOUDFLARE_API_KEY} # Same as traefik
      - DEFAULT_TTL=1
      - TARGET_DOMAIN=${DOMAIN_NAME}
      - DOMAIN1=${DOMAIN_NAME}
      - DOMAIN1_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - DOMAIN1_PROXIED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - diun.enable=true
      # Add hosts specified in rules here to force cf-companion to create the CNAMEs
      # Since cf-companion creates CNAMEs based on host rules, this a workaround for non-docker/external apps
      - traefik.http.routers.cf-companion.rule=HostHeader(`pihole.${DOMAIN_NAME}`,`hassio.${DOMAIN_NAME}`)
      
  # Authelia - IAM
  authelia:
    image: authelia/authelia:4.37.5
    container_name: authelia
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 1024m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    expose:
      - 9091
    volumes:
      - ${USER_DIR}/authelia/config:/config
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`authelia.${DOMAIN_NAME}`)
      - traefik.http.routers.authelia.middlewares=chain-authelia@file
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      
  # Google OAuth - Single Sign On using OAuth 2.0 for Traefik 2.2
  oauth:
    image: thomseddon/traefik-forward-auth:2.2.0
    # image: thomseddon/traefik-forward-auth:2.1-arm # Use this image with Raspberry Pi
    container_name: oauth
    restart: unless-stopped
    cpus: 0.01
    mem_limit: 8m
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID=${GOOGLE_CLIENT_ID}
      - CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET=${OAUTH_SECRET}
      - COOKIE_DOMAIN=${DOMAIN_NAME}
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.${DOMAIN_NAME}
      - URL_PATH=/_oauth
      # - WHITELIST=${MY_EMAIL}
      - WHITELIST=${CLOUDFLARE_EMAIL}
      - LOG_LEVEL=warn
      - LOG_FORMAT=text
      - LIFETIME=2592000 # 30 days
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.oauth.entrypoints=websecure
      - traefik.http.routers.oauth.rule=Host(`oauth.${DOMAIN_NAME}`)
      - traefik.http.routers.oauth.middlewares=chain-oauth@file
      - traefik.http.services.oauth.loadbalancer.server.port=4181
