# https://www.smarthomebeginner.com/docker-authelia-tutorial/
server:
  address: tcp://0.0.0.0:9091/
log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true
theme: dark
# https://www.grc.com/passwords.htm
identity_validation:
  reset_password:
    # jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE
totp:
  issuer: davydehaas.nl
  digits: 6
  period: 30
  skew: 1
authentication_backend:
  file:
    path: /config/users.yaml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.
# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/24
    - name: VPN
      networks:
        - 10.9.0.0/16
  rules:
    - domain: authelia.davydehaas.nl
      policy: bypass
      networks:
        - internal
    - domain:
        - "davydehaas.nl"
        - "*.davydehaas.nl"
      policy: two_factor
session:
  name: authelia_session
  # https://www.grc.com/passwords.htm
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  same_site: lax
  cookies:
    - domain: davydehaas.nl
      authelia_url: https://authelia.davydehaas.nl
      default_redirection_url: https://davydehaas.nl
regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h
storage:
  encryption_key: SECRET_GOES_HERE
  local:
    path: /config/db.sqlite3
notifier:
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notification.txt
