# https://www.smarthomebeginner.com/docker-authelia-tutorial/
server:
  host: 0.0.0.0
  port: 9091
log: 
  level: warn

# https://www.grc.com/passwords.htm
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

default_redirection_url: https://authelia.davydehaas.nl

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    - domain: authelia.davydehaas.nl
      policy: bypass
    - domain:
        - "*.davydehaas.nl"
        - "davydehaas.nl"
      policy: two_factor

session:
  name: authelia_session
  # https://www.grc.com/passwords.htm
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: davydehaas.nl # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3
  # encryption_key: SECRET_GOES_HERE

notifier:
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notification.txt