# https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration
api:
  insecure: false
  dashboard: true

experimental:
  http3: true
  hub: true

global:
  checkNewVersion: true
  sendAnonymousUsage: false

hub:
  tls:
    insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: reverse-proxy_default
    swarmMode: false
    watch: true
  file:
    directory: /config/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
    watch: true # Only works on top level files in the rules folder

metrics:
  prometheus:
    addRoutersLabels: true
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

tracing:
  jaeger:
    samplingType: const
    samplingParam: 1.0
    gen128Bit: true
    samplingServerURL: http://jaeger:5778/sampling
    localAgentHostPort: jaeger:6831
    propagation: jaeger

accessLog:
  filePath: /access.log
  bufferingSize: 100
  filters:
    statuscodes: 400-499
    retryAttempts: true
    minDuration: 10ms

log:
  filePath: /traefik.log
  level: WARN

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  dns-resolver-cloudflare:
    acme:
      keyType: EC384
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing

entryPoints:
  traefik:
    address: ":8080"
  tcp:
   address: ":3179/tcp"
  udp:
   address: ":3179/udp"
   udp:
      timeout: 10s
  web:
    address: ":80"
    http:
      redirections:
        EntryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: dns-resolver-cloudflare
    # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
    forwardedHeaders:
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
