name: main
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
env:
  UID: 1400
  GID: 1400
  TZ: Etc/UTC
  TARGET_DIR: /home/homelab/compose/reverse-proxy
  USER_DIR: /home/homelab/reverse-proxy
  DOMAIN_NAME: davydehaas.nl
jobs:
   deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files
        run: |
          rsync ./compose.yaml homelab@${{ secrets.SSH_HOST }}:${{ env.TARGET_DIR }}
          rsync --archive --recursive  ./authelia homelab@${{ secrets.SSH_HOST }}:${{ env.USER_DIR }}
          rsync --archive --recursive  ./traefik homelab@${{ secrets.SSH_HOST }}:${{ env.USER_DIR }}
      - name: Start containers
        run: |
          ssh homelab@${{ secrets.SSH_HOST }} /bin/bash << ENDSSH
          cd ${{ env.TARGET_DIR }}

          cat << EOF > .env
          UID=${{ env.UID }}
          GID=${{ env.GID }}
          TZ=${{ env.TZ }}
          USER_DIR=${{ env.USER_DIR }}
          DOMAIN_NAME=${{ env.DOMAIN_NAME }}
          CLOUDFLARE_EMAIL=${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}
          OAUTH_SECRET=${{ secrets.OAUTH_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          EOF
          
          docker compose up -d

          ENDSSH
