name: Traefik reverse proxy
on:
  push:
    branches:
    - main
    
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
  
env:
  TARGET_DIR: ./docker-compose/reverse-proxy
  PGID: 998
  PUID: 997
  TZ: Europe/Amsterdam
  DOMAIN_NAME: davydehaas.nl

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        rm: true
    - name: SSH SCP | Copy container configurations
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: ./docker-compose.yml
        target: ${{ env.TARGET_DIR }}
        strip_components: 1
        rm: true
    - name: SSH | Start container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.TARGET_DIR }}
          
          echo 'PGID=${{ env.PGID }}' >> .env
          echo 'PUID=${{ env.PUID }}' >> .env
          echo 'TZ=${{ env.TZ }}' >> .env
          echo 'DOMAIN_NAME=${{ env.DOMAIN_NAME }}' >> .env
          
          echo 'CLOUDFLARE_EMAIL=${{ secrets.CLOUDFLARE_EMAIL }}' >> .env
          echo 'CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}' >> .env

          docker-compose up -d
