name: NGINX reverse proxy
on:
  push:
    branches:
    - master

env:
  DOCKER_IMAGE: davydehaas98/reverse-proxy:latest
  TARGET_DIRECTORY: ./docker/reverse-proxy

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker build -t ${{ env.DOCKER_IMAGE }} .
        docker push ${{ env.DOCKER_IMAGE }}
  deploy:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH SCP | Copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "docker-compose.yml"
        target: ${{ env.TARGET_DIRECTORY }}
    - name: SSH | Start container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.TARGET_DIRECTORY }}
          docker-compose pull ${{ env.DOCKER_IMAGE }}
          docker-compose up -d --remove-orphans
          docker image prune --force
